### PR TITLE
Profile schema

### LINKED ISSUE #5: Profile Schema
## Description

We need to create the endpoints for creating a new profile and getting a profile.

## Spec

- [ ] POST: /v1/profiles with a _valid json object_ for a user which _does not have a profile_ is successful
- [ ] POST: /v1/profiles fails if the json is malformed
- [ ] POST: /v1/profiles fails if there is already a profile
- [ ] GET: /v1/profiles/$id produces a user's profile, if it exists.
- [ ] GET: /v1/profile produces the current user's profile.

### PR DESCRIPTION
**Pull request by Ross3102**
Created types for data sent to and from the profiles API, set up Jest for the project and created tests for the API, and added data validation with AJV.

Closes #5

### CODE REVIEW

**Review by nicoledanuwidjaja — APPROVED** [review]
Great job with the testing! Really appreciate the work you guys put into this. :)

One note: I tried debugging for a few hours but I wasn't able to figure out why the test was flaky, but I'm pretty sure that it's a mongoose database connection testing setup issue. I think it's safe to revisit that later on since it doesn't seem to be caused by the code.

File: repositories/profile.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
+import { Schema, Document } from 'mongoose';
+import ProfileModel from '../dbmodels/profile';
+import HTTPError from '../exceptions/HTTPError';
+import IProfile from '../types/dbtypes/profile';
+
+// Gets a profile by id
+export const get_profile_by_id = async (id: string): Promise<IProfile> => {
+  return await ProfileModel.findById(id).then(
```
Comment (nicoledanuwidjaja) [inline repositories/profile.ts:8]: This only handles errors returned because a profile wasn't found. Instead of this closure, we should simplify this to:
```
try {
  const docs: IProfile | null | undefined = await ProfileModel.findById(id);
  if (!docs) {
     return Promise.reject(new HTTPError('Profile not found', 404));
  }
} catch (e) {
    // this should be mongo specific errors, so perhaps we return some error on the server side....?
    return Promise.reject(new HTTPError('Ahhh an unknown error?', 500));
}

**Review by nicoledanuwidjaja — CHANGES_REQUESTED** [review]
I lied, there are a few more things i noticed now that it's 7pm

**Review by connorlbark — APPROVED** [review]
this looks actually so amazing thank you to everyone who contributed to this Pr this is HUGE

**Review by nicoledanuwidjaja — APPROVED** [review]
LGTM ahhhh
